services:
  web:
    build: .
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env   # Same .env file
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data    # this is where PostgreSQL stores all its data inside the container.

volumes:
  postgres_data:
